require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"

require "user.cmp"
require "user.lsp"

require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"

require "user.autopairs"
require "user.editorconfig-vim"
require "user.kommentary"
require "user.quick-scope"
require "user.vim-test"

require "user.alpha"
require "user.which-key"
require "user.autocommands"
